// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vfifo_buffer.cpp"
#include "Vfifo_buffer___024root__DepSet_hfda39229__0.cpp"
#include "Vfifo_buffer___024root__DepSet_h2b47efb1__0.cpp"
#include "Vfifo_buffer__Trace__0.cpp"
#include "Vfifo_buffer___024root__Slow.cpp"
#include "Vfifo_buffer___024root__DepSet_hfda39229__0__Slow.cpp"
#include "Vfifo_buffer___024root__DepSet_h2b47efb1__0__Slow.cpp"
#include "Vfifo_buffer__Syms.cpp"
#include "Vfifo_buffer__Trace__0__Slow.cpp"
#include "Vfifo_buffer__TraceDecls__0__Slow.cpp"
